// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: media/torrenti/v1/index_service.proto

/*
Package torrentiv1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package torrentiv1

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code

var (
	_ io.Reader
	_ status.Status
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_TorrentIndexService_IndexTorrent_0(ctx context.Context, marshaler runtime.Marshaler, client TorrentIndexServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq IndexTorrentRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.IndexTorrent(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_TorrentIndexService_IndexTorrent_0(ctx context.Context, marshaler runtime.Marshaler, server TorrentIndexServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq IndexTorrentRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.IndexTorrent(ctx, &protoReq)
	return msg, metadata, err
}

func request_TorrentIndexService_Stat_0(ctx context.Context, marshaler runtime.Marshaler, client TorrentIndexServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq StatRequest
	var metadata runtime.ServerMetadata

	msg, err := client.Stat(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_TorrentIndexService_Stat_0(ctx context.Context, marshaler runtime.Marshaler, server TorrentIndexServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq StatRequest
	var metadata runtime.ServerMetadata

	msg, err := server.Stat(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterTorrentIndexServiceHandlerServer registers the http handlers for service TorrentIndexService to "mux".
// UnaryRPC     :call TorrentIndexServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterTorrentIndexServiceHandlerFromEndpoint instead.
func RegisterTorrentIndexServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server TorrentIndexServiceServer) error {
	mux.Handle("POST", pattern_TorrentIndexService_IndexTorrent_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		ctx, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/media.torrenti.v1.TorrentIndexService/IndexTorrent", runtime.WithHTTPPathPattern("/torrents/index"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_TorrentIndexService_IndexTorrent_0(ctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_TorrentIndexService_IndexTorrent_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	mux.Handle("GET", pattern_TorrentIndexService_Stat_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		ctx, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/media.torrenti.v1.TorrentIndexService/Stat", runtime.WithHTTPPathPattern("/torrents/stat"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_TorrentIndexService_Stat_0(ctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_TorrentIndexService_Stat_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterTorrentIndexServiceHandlerFromEndpoint is same as RegisterTorrentIndexServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterTorrentIndexServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterTorrentIndexServiceHandler(ctx, mux, conn)
}

// RegisterTorrentIndexServiceHandler registers the http handlers for service TorrentIndexService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterTorrentIndexServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterTorrentIndexServiceHandlerClient(ctx, mux, NewTorrentIndexServiceClient(conn))
}

// RegisterTorrentIndexServiceHandlerClient registers the http handlers for service TorrentIndexService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "TorrentIndexServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "TorrentIndexServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "TorrentIndexServiceClient" to call the correct interceptors.
func RegisterTorrentIndexServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client TorrentIndexServiceClient) error {
	mux.Handle("POST", pattern_TorrentIndexService_IndexTorrent_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		ctx, err = runtime.AnnotateContext(ctx, mux, req, "/media.torrenti.v1.TorrentIndexService/IndexTorrent", runtime.WithHTTPPathPattern("/torrents/index"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_TorrentIndexService_IndexTorrent_0(ctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_TorrentIndexService_IndexTorrent_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	mux.Handle("GET", pattern_TorrentIndexService_Stat_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		ctx, err = runtime.AnnotateContext(ctx, mux, req, "/media.torrenti.v1.TorrentIndexService/Stat", runtime.WithHTTPPathPattern("/torrents/stat"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_TorrentIndexService_Stat_0(ctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_TorrentIndexService_Stat_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	return nil
}

var (
	pattern_TorrentIndexService_IndexTorrent_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"torrents", "index"}, ""))

	pattern_TorrentIndexService_Stat_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"torrents", "stat"}, ""))
)

var (
	forward_TorrentIndexService_IndexTorrent_0 = runtime.ForwardResponseMessage

	forward_TorrentIndexService_Stat_0 = runtime.ForwardResponseMessage
)
